ls:
  "{frontend,backend}/src":
    .js: camelCase | point.case
    .jsx: camelCase | PascalCase | point.case
    .ts: camelCase | point.case
    .tsx: camelCase | PascalCase | point.case
    .d.ts: camelCase
    .dir: camelCase

ignore:
  - frontend/src/generated
  - backend/src/generated
